### ISSUE TITLE
Need to allow sort by elasticsearch through skyRepo

### ISSUE THREAD

**Issue by winonadeb** [Eduworks/ew#4]
In instances where skyRepo contains a large number of objects, it would be much more efficient if the skyrepo search would allow us to pass along sort criteria to elasticsearch. We would also like visibility into the relativity _score value that elasticsearch uses to sort by default, so that the UI can make decisions on what should or should not be shown to the user, and how to do so.

**Comment by Lomilar** [comment]
Sorting by "name" does not work with our ElasticSearch mappings, it requires "name.keyword" -- I modified the code to include a ".keyword" append to any sort URL parameter.

Fixed in 2c50b7985cb6b8a6e2034f6a01ceec6b27e153e3
